{{- if .Values.ingressDocker.enabled }}

{{- $serviceName := include "nexus.fullname" . -}}
{{- if .Values.nexusProxy.svcName }}
  {{- $serviceName = .Values.nexusProxy.svcName -}}
{{- end }}

{{- $servicePort := .Values.nexus.dockerPort -}}
{{- if .Values.nexusProxy.enabled }}
  {{- $servicePort = .Values.nexusProxy.port -}}
{{- end }}

{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "nexus.ingress.docker" . }}
  namespace: {{ template "nexus.namespace" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
    {{- range $key, $value := .Values.ingressDocker.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingressDocker.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingressDocker.className }}
  ingressClassName: {{ .Values.ingressDocker.className }}
  {{- end }}
  rules:
  {{- if .Values.nexusProxy.env.nexusDockerHost }}
    - host: {{ .Values.nexusProxy.env.nexusDockerHost }}
      http:
        paths:
          - path: {{ .Values.ingressDocker.path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: {{ .Values.ingressDocker.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end }}
  {{- with .Values.ingressDocker.rules }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- if .Values.ingressDocker.tls.enabled }}
  tls:
    - hosts:
      {{- if .Values.nexusProxy.env.nexusDockerHost }}
        - {{ .Values.nexusProxy.env.nexusDockerHost }}
      {{- end }}
      {{- if .Values.ingressDocker.tls.secretName }}
      secretName: {{ .Values.ingressDocker.tls.secretName | quote }}
      {{- end }}
  {{- with .Values.ingressDocker.tls.hosts }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
{{- end }}
