apiVersion: v1
appVersion: 7.3.1
description: A Helm chart for deploying Eclipse Che to Kubernetes
name: che
version: 0.1.6
keywords:
- che
- eclipse
maintainers:
home: https://www.eclipse.org/che/
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
deprecated: true
